spring.profiles.active: dev
mybatis.type-aliases-package: com.chinamobile.iot.xiaoyan.bgapi.entity
#Mapper.xml所在的位置
mybatis.mapper-locations: classpath:/mybatis/mapper/*.xml
mybatis.config-location: classpath:/mybatis/mybatis-config.xml
#pagehelper分页插件配置
pagehelper.helperDialect: mysql
pagehelper.reasonable: true
pagehelper.supportMethodsArguments: true
pagehelper.params.count: countSql



